name: 'Test Action'
description: 'A composite action to run tests using Dockerfile.test from this repo'
runs:
  using: 'composite'
  steps:
    - name: Checkout action repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: image
        path: /tmp

    - name: Load image
      run: docker load -i /tmp/image.tar
      shell: bash

    - name: Build
      id: build
      uses: docker/build-push-action@v2
      with:
        file: ${{ github.action_path }}/Dockerfile.test
        push: false
        tags: tester:latest
        build-args: |
          BASE_IMAGE=image:latest

    - name: Run tests
      run: docker run --rm tester:latest
      shell: bash
